
import java.io.IOException;
import javax.swing.JButton;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.Date;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author alexandrezamberlan
 */
public class JFrame_Servidor extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_Servidor
     */
    public JFrame_Servidor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField_portaServidor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField_apelido = new javax.swing.JTextField();
        jButton_conectar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField_mensagem = new javax.swing.JTextField();
        jButton_enviar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField_apelidoCliente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField_enderecoCliente = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_mensagens = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Porta do servidor: ");

        jLabel2.setText("Apelido:");

        jButton_conectar.setText("Conectar");
        jButton_conectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_conectarActionPerformed(evt);
            }
        });

        jLabel3.setText("Mensagem: ");

        jTextField_mensagem.setEditable(false);

        jButton_enviar.setText("Enviar");
        jButton_enviar.setEnabled(false);
        jButton_enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_enviarActionPerformed(evt);
            }
        });

        jLabel4.setText("Apelido do cliente: ");

        jTextField_apelidoCliente.setEditable(false);
        jTextField_apelidoCliente.setFocusable(false);

        jLabel5.setText("Endereço do cliente: ");

        jTextField_enderecoCliente.setEditable(false);
        jTextField_enderecoCliente.setFocusable(false);

        jTextArea_mensagens.setEditable(false);
        jTextArea_mensagens.setColumns(20);
        jTextArea_mensagens.setRows(5);
        jTextArea_mensagens.setFocusable(false);
        jScrollPane1.setViewportView(jTextArea_mensagens);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_portaServidor, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                            .addComponent(jTextField_apelidoCliente))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_apelido, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_conectar)
                                .addGap(0, 18, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_enderecoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_mensagem)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_enviar)
                        .addGap(18, 18, 18))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_portaServidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_apelido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_conectar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField_apelidoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField_enderecoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_mensagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_enviar))
                .addGap(8, 8, 8))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_conectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_conectarActionPerformed
        // TODO add your handling code here:
        if (jTextField_portaServidor.getText().isEmpty() || jTextField_apelido.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Para conectar é preciso definir porta e apelido");
        } else {
            try {
                servidor = new ServerSocket(Integer.parseInt(jTextField_portaServidor.getText()));

                jTextField_portaServidor.setEditable(false);
                jTextField_apelido.setEditable(false);
                jButton_conectar.setEnabled(false);

                cliente = servidor.accept();
                jTextField_enderecoCliente.setText(cliente.getInetAddress().toString());
                jTextField_mensagem.setEditable(true);
                jButton_enviar.setEnabled(true);

                new Thread() {
                    @Override
                    public void run() {
                        Date dataAtual = new Date();
                        while (true) {
                            jTextArea_mensagens.setText("["+ dataAtual + "]: " + Comunicador.receberMensagem(cliente) + "\n");  
                        }
                    }
                }.start();

            } catch (IOException | NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Erro ao conectar o servidor");
            }
        }

    }//GEN-LAST:event_jButton_conectarActionPerformed

    private void jButton_enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_enviarActionPerformed
        // TODO add your handling code here:
        if (jTextField_mensagem.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this,"Antes de enviar, é preciso digitar!!");
        } else {
            Comunicador.enviarMensagem(cliente, jTextField_mensagem.getText());
            Date dataAtual = new Date();
            jTextArea_mensagens.append("["+ dataAtual + "] Você escreveu: " + jTextField_mensagem.getText() + "\n");
            jTextField_mensagem.setText("");
        }
    }//GEN-LAST:event_jButton_enviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_Servidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_Servidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_Servidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_Servidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_Servidor().setVisible(true);
            }
        });
    }

    ServerSocket servidor;
    Socket cliente;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_conectar;
    private javax.swing.JButton jButton_enviar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea_mensagens;
    private javax.swing.JTextField jTextField_apelido;
    private javax.swing.JTextField jTextField_apelidoCliente;
    private javax.swing.JTextField jTextField_enderecoCliente;
    private javax.swing.JTextField jTextField_mensagem;
    private javax.swing.JTextField jTextField_portaServidor;
    // End of variables declaration//GEN-END:variables

    public JButton getjButton_conectar() {
        return jButton_conectar;
    }

    public void setjButton_conectar(JButton jButton_conectar) {
        this.jButton_conectar = jButton_conectar;
    }

    public JButton getjButton_enviar() {
        return jButton_enviar;
    }

    public void setjButton_enviar(JButton jButton_enviar) {
        this.jButton_enviar = jButton_enviar;
    }

    public JTextArea getjTextArea_mensagens() {
        return jTextArea_mensagens;
    }

    public void setjTextArea_mensagens(JTextArea jTextArea_mensagens) {
        this.jTextArea_mensagens = jTextArea_mensagens;
    }

    public JTextField getjTextField_enderecoCliente() {
        return jTextField_enderecoCliente;
    }

    public void setjTextField_enderecoCliente(JTextField jTextField_enderecoCliente) {
        this.jTextField_enderecoCliente = jTextField_enderecoCliente;
    }

    public JTextField getjTextField_mensagem() {
        return jTextField_mensagem;
    }

    public void setjTextField_mensagem(JTextField jTextField_mensagem) {
        this.jTextField_mensagem = jTextField_mensagem;
    }
}
