/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package comunicacao;

import javax.swing.JOptionPane;

/**
 *
 * @author alexandrezamberlan
 */
public class JFrame_chatJGROUPS extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_chatJGROUPS
     */
    public JFrame_chatJGROUPS() {
        initComponents();
        jButton_sairGrupo.setEnabled(false);
        jTextArea_mensagensGerais.setEditable(false);
        jTextArea_mensagensGerais.setFocusable(false);
        jTextField_mensagemParaGrupo.setEnabled(false);
        jButton_enviarMensagemGrupo.setEnabled(false);
        jComboBox_listaParticipantesGrupo.setEnabled(false);
        jTextField_mensagemParaParticipante.setEnabled(false);
        jButton_enviarParticipante.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_mensagensGerais = new javax.swing.JTextArea();
        jTextField_apelido = new javax.swing.JTextField();
        jButton_entrarGrupo = new javax.swing.JButton();
        jButton_sairGrupo = new javax.swing.JButton();
        jTextField_mensagemParaGrupo = new javax.swing.JTextField();
        jComboBox_listaParticipantesGrupo = new javax.swing.JComboBox<>();
        jTextField_mensagemParaParticipante = new javax.swing.JTextField();
        jButton_enviarMensagemGrupo = new javax.swing.JButton();
        jButton_enviarParticipante = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chat com JGroups");

        jLabel1.setText("Apelido: ");

        jLabel2.setText("Mensagem para o grupo: ");

        jLabel3.setText("Mensagem excluiva para: ");

        jTextArea_mensagensGerais.setColumns(20);
        jTextArea_mensagensGerais.setRows(5);
        jScrollPane1.setViewportView(jTextArea_mensagensGerais);

        jButton_entrarGrupo.setText("Entrar");
        jButton_entrarGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_entrarGrupoActionPerformed(evt);
            }
        });

        jButton_sairGrupo.setText("Sair");

        jComboBox_listaParticipantesGrupo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o participante", " " }));

        jButton_enviarMensagemGrupo.setText("Enviar Grupo");

        jButton_enviarParticipante.setText("Enviar Part.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox_listaParticipantesGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_mensagemParaParticipante))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_apelido, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_entrarGrupo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_sairGrupo))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_mensagemParaGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton_enviarParticipante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_enviarMensagemGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                        .addGap(16, 16, 16))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_apelido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_entrarGrupo)
                    .addComponent(jButton_sairGrupo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_mensagemParaGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_enviarMensagemGrupo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox_listaParticipantesGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_mensagemParaParticipante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_enviarParticipante))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_entrarGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_entrarGrupoActionPerformed
        // TODO add your handling code here:
        if (jTextField_apelido.getText().equals("")) {
            JOptionPane.showMessageDialog(this,"Você precisa informar um apelido!!!");
        } else {
            jButton_entrarGrupo.setEnabled(false);
            jButton_sairGrupo.setEnabled(true);
            jTextField_mensagemParaGrupo.setEnabled(true);
            jButton_enviarMensagemGrupo.setEnabled(true);
            jComboBox_listaParticipantesGrupo.setEnabled(true);
            jTextField_mensagemParaParticipante.setEnabled(true);
            jButton_enviarParticipante.setEnabled(true);
            jTextField_apelido.setText(jTextField_apelido.getText().toUpperCase());
            jTextField_apelido.setEditable(false);
            jTextField_apelido.setFocusable(false);
        }
    }//GEN-LAST:event_jButton_entrarGrupoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_chatJGROUPS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_chatJGROUPS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_chatJGROUPS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_chatJGROUPS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_chatJGROUPS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_entrarGrupo;
    private javax.swing.JButton jButton_enviarMensagemGrupo;
    private javax.swing.JButton jButton_enviarParticipante;
    private javax.swing.JButton jButton_sairGrupo;
    private javax.swing.JComboBox<String> jComboBox_listaParticipantesGrupo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea_mensagensGerais;
    private javax.swing.JTextField jTextField_apelido;
    private javax.swing.JTextField jTextField_mensagemParaGrupo;
    private javax.swing.JTextField jTextField_mensagemParaParticipante;
    // End of variables declaration//GEN-END:variables
}
