import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.KeyStroke;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author usrlab01
 */
public class GameServer extends javax.swing.JFrame {

    static PlayerController p1;
    static BallController ball;
    static ScoreController score;
    
    Thread pt1;
    Thread ballt;
    
    static int porta = 1201;
    static ServerSocket servidor;
    static Socket cliente;
    static ObjectInputStream leitor;
    static ObjectOutputStream escritor;
    
    public GameServer() {
        initComponents();
        p1 = new PlayerController(jButtonPlayer1, jPanelGame);
        score = new ScoreController(jLabelScorePlayer1, jLabelScorePlayer2, jLabelInstructions);
        ball = new BallController(jPanelGame, jButtonBall, jButtonPlayer1, jButtonPlayer2, score);
        
        pt1 = new Thread(p1);
        ballt = new Thread(ball);
        jPanelGame.requestFocus();
        
        new Thread() {
            @Override
            public void run() {
                try {
                    servidor = new ServerSocket(porta);
                    System.out.println("Servidor no ar.....");
                    cliente = servidor.accept();
                    escritor = new ObjectOutputStream(cliente.getOutputStream());
                    leitor = new ObjectInputStream(cliente.getInputStream());
                    //para enviar ao jogador 1
                    //ATENÇAO... a sequencia de instanciacao dever ser 1o o saida e 2o o entrada
                   
                    while (true) {
                        JButton btn = (JButton)leitor.readObject();
                        jButtonPlayer2.setLocation(btn.getX(), btn.getY());
                        
                        escritor.flush();
                        escritor.writeObject(jButtonPlayer1);
                       /* escritor.flush();
                        escritor.writeObject(jButtonBall);*/
                    }
                } catch (Exception e) {
                    System.out.println("Erro: " + e.getMessage());
                }
            }
        }.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelGame = new javax.swing.JPanel();
        jButtonPlayer2 = new javax.swing.JButton();
        jButtonPlayer1 = new javax.swing.JButton();
        jButtonBall = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabelScorePlayer1 = new javax.swing.JLabel();
        jLabelScorePlayer2 = new javax.swing.JLabel();
        jLabelInstructions = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(775, 620));
        setMinimumSize(new java.awt.Dimension(770, 536));
        setPreferredSize(new java.awt.Dimension(775, 577));

        jPanelGame.setBackground(new java.awt.Color(51, 51, 51));
        jPanelGame.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelGame.setPreferredSize(new java.awt.Dimension(746, 430));
        jPanelGame.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanelGameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPanelGameKeyReleased(evt);
            }
        });

        jButtonPlayer2.setBackground(new java.awt.Color(51, 204, 255));
        jButtonPlayer2.setBorder(null);
        jButtonPlayer2.setFocusable(false);

        jButtonPlayer1.setBackground(new java.awt.Color(255, 153, 51));
        jButtonPlayer1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonPlayer1.setBorder(null);
        jButtonPlayer1.setFocusable(false);

        jButtonBall.setBackground(new java.awt.Color(255, 255, 255));
        jButtonBall.setFocusable(false);
        jButtonBall.setMaximumSize(new java.awt.Dimension(33, 33));
        jButtonBall.setMinimumSize(new java.awt.Dimension(33, 33));
        jButtonBall.setName("ball"); // NOI18N
        jButtonBall.setPreferredSize(new java.awt.Dimension(33, 33));

        javax.swing.GroupLayout jPanelGameLayout = new javax.swing.GroupLayout(jPanelGame);
        jPanelGame.setLayout(jPanelGameLayout);
        jPanelGameLayout.setHorizontalGroup(
            jPanelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonPlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(348, 348, 348)
                .addComponent(jButtonBall, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 349, Short.MAX_VALUE)
                .addComponent(jButtonPlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelGameLayout.setVerticalGroup(
            jPanelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGameLayout.createSequentialGroup()
                .addGroup(jPanelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonPlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelGameLayout.createSequentialGroup()
                            .addGap(181, 181, 181)
                            .addComponent(jButtonBall, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelGameLayout.createSequentialGroup()
                            .addGap(150, 150, 150)
                            .addComponent(jButtonPlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(191, Short.MAX_VALUE))
        );

        jPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanel1KeyPressed(evt);
            }
        });

        jLabelScorePlayer1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelScorePlayer1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelScorePlayer1.setText("0");
        jLabelScorePlayer1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelScorePlayer2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelScorePlayer2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelScorePlayer2.setText("0");
        jLabelScorePlayer2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelInstructions.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelInstructions.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelInstructions.setText("Inicie com Espaço");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabelScorePlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelInstructions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelScorePlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelScorePlayer2)
                    .addComponent(jLabelScorePlayer1)
                    .addComponent(jLabelInstructions))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelGame, javax.swing.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelGame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1KeyPressed

    private void jPanelGameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanelGameKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_W)
        {
           p1.setMoveUp(true);
           if (pt1.isAlive()) 
            {
                pt1.interrupt();
            }
            pt1 = new Thread(p1);
            pt1.start();
        }

        if (evt.getKeyCode() == KeyEvent.VK_S){
           p1.setMoveDown(true);
           if (pt1.isAlive()) 
            {
                pt1.interrupt();
            }
            pt1 = new Thread(p1);
            pt1.start();
        }
        
        if (evt.getKeyCode() == KeyEvent.VK_SPACE){
           if (!ballt.isAlive()) 
            {
                ballt = new Thread(ball);
                ballt.start();
                score.resetScore();
            }else{
               ball.startRound();
           }
        }
    }//GEN-LAST:event_jPanelGameKeyPressed

    private void jPanelGameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanelGameKeyReleased
        System.out.println("servidor mexendo.....");
        
        if (evt.getKeyCode() == KeyEvent.VK_W){
            p1.setMoveUp(false);
            if (pt1.isAlive()) 
            {
                pt1.interrupt();
            }
         }

         if (evt.getKeyCode() == KeyEvent.VK_S){
            p1.setMoveDown(false);
            if (pt1.isAlive()) 
            {
                pt1.interrupt();
            }
         }

         /*if (evt.getKeyCode() == KeyEvent.VK_UP){
            p2.setMoveUp(false);
            if (pt2.isAlive()) 
            {
                pt2.interrupt();
            }
         }

         if (evt.getKeyCode() == KeyEvent.VK_DOWN){
            p2.setMoveDown(false);
            if (pt2.isAlive()) 
            {
                pt2.interrupt();
            }
         }*/
    }//GEN-LAST:event_jPanelGameKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameServer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JButton jButtonBall;
    private static javax.swing.JButton jButtonPlayer1;
    private static javax.swing.JButton jButtonPlayer2;
    private javax.swing.JLabel jLabelInstructions;
    private javax.swing.JLabel jLabelScorePlayer1;
    private javax.swing.JLabel jLabelScorePlayer2;
    private javax.swing.JPanel jPanel1;
    private static javax.swing.JPanel jPanelGame;
    // End of variables declaration//GEN-END:variables
}
