import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.HashSet;
import java.util.Random;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author usrlab01
 */
public class JFrame_jogoFrutinha extends javax.swing.JFrame {

    public Set<Integer> pressed = new HashSet<>();

    JFrame meuFrame;

    public JFrame_jogoFrutinha() {
        initComponents();
        meuFrame = this;
        new Thread() {
            public void run() {
                sorteiaPosicoes();
            }
        }.start();

        new Thread() {
            public void run() {
                while (true) {
                    try {
                        verificaTeclas();
                        try {
                            sleep(10);
                        } catch (InterruptedException ex) {
                            Logger.getLogger(JFrame_jogoFrutinha.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    } catch (Exception e) {
                        System.out.println("Deu pau na concorrência");
                    }
                }

            }
        }.start();
    }

    private void sorteiaPosicoes() {
        Random gerador = new Random();
        JOptionPane.showMessageDialog(this, "Pronto para começar????");
        jButton_fruta.setBounds(gerador.nextInt(this.getWidth() - 80), gerador.nextInt(this.getHeight() - 80), jButton_fruta.getWidth(), jButton_fruta.getHeight());
        jButton_jogador1.setBounds(gerador.nextInt(this.getWidth() - 80), gerador.nextInt(this.getHeight() - 80),
                jButton_jogador1.getWidth(), jButton_jogador1.getHeight());
        jButton_jogador2.setBounds(gerador.nextInt(this.getWidth() - 80), gerador.nextInt(this.getHeight() - 80),
                jButton_jogador2.getWidth(), jButton_jogador2.getHeight());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jButton_jogador1 = new javax.swing.JButton();
        jButton_jogador2 = new javax.swing.JButton();
        jButton_fruta = new javax.swing.JButton();
        jTextField_jogador1 = new javax.swing.JTextField();
        jTextField_jogador2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Jogo da frutinha");

        jButton_jogador1.setText("1");
        jButton_jogador1.setFocusable(false);

        jButton_jogador2.setText("2");
        jButton_jogador2.setFocusable(false);

        jButton_fruta.setBackground(new java.awt.Color(255, 204, 0));
        jButton_fruta.setText("@");
        jButton_fruta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton_frutaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jButton_frutaKeyReleased(evt);
            }
        });

        jTextField_jogador1.setEditable(false);
        jTextField_jogador1.setFocusable(false);

        jTextField_jogador2.setEditable(false);
        jTextField_jogador2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField_jogador2.setFocusable(false);

        jLabel1.setText(":Pontos Jogador2");

        jLabel2.setText("Pontos Jogador1:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_jogador1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 404, Short.MAX_VALUE)
                        .addComponent(jTextField_jogador2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_jogador1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_jogador2)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(350, 350, 350)
                .addComponent(jButton_fruta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_jogador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_jogador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jButton_jogador2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jButton_jogador1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 205, Short.MAX_VALUE)
                .addComponent(jButton_fruta, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );

        jButton_jogador1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>                        

    public void verificaTeclas() {
        for (Integer c : pressed) {
            switch (c) {
                case KeyEvent.VK_UP:
                    new Thread() {
                        @Override
                        public void run() {
                            Movimenta.irCima(jButton_jogador2);
                        }
                    }.start();
                    break;
                case KeyEvent.VK_DOWN:
                    new Thread() {
                        @Override
                        public void run() {
                            Movimenta.irBaixo(jButton_jogador2, altura);
                        }
                    }.start();
                    break;
                case KeyEvent.VK_LEFT:
                    new Thread() {
                        @Override
                        public void run() {
                            Movimenta.irEsquerda(jButton_jogador2);
                        }
                    }.start();
                    break;
                case KeyEvent.VK_RIGHT:
                    new Thread() {
                        @Override
                        public void run() {
                            Movimenta.irDireita(jButton_jogador2, largura);
                        }
                    }.start();
                    break;
                case KeyEvent.VK_W:
                    new Thread() {
                        @Override
                        public void run() {
                            Movimenta.irCima(jButton_jogador1);
                        }
                    }.start();
                    break;
                case KeyEvent.VK_S:
                    new Thread() {
                        @Override
                        public void run() {
                            Movimenta.irBaixo(jButton_jogador1, altura);
                        }
                    }.start();
                    break;
                case KeyEvent.VK_A:
                    new Thread() {
                        @Override
                        public void run() {
                            Movimenta.irEsquerda(jButton_jogador1);
                        }
                    }.start();
                    break;
                case KeyEvent.VK_D:
                    new Thread() {
                        @Override
                        public void run() {
                            Movimenta.irDireita(jButton_jogador1, largura);
                        }
                    }.start();
                    break;
            }
        }
        if (Movimenta.pegou(jButton_fruta, jButton_jogador1)) {
            Movimenta.sorteiaPosicao(jButton_fruta, meuFrame);
            pontosJogador1++;
            jTextField_jogador1.setText("" + pontosJogador1);
        }
        if (Movimenta.pegou(jButton_fruta, jButton_jogador2)) {
            Movimenta.sorteiaPosicao(jButton_fruta, meuFrame);
            pontosJogador2++;
            jTextField_jogador2.setText("" + pontosJogador2);
        }
    }
    private void jButton_frutaKeyPressed(java.awt.event.KeyEvent evt) {                                         
        // TODO add your handling code here:
        largura = this.getWidth();
        altura = this.getHeight();
        System.out.println(evt.getKeyCode() + ", " + evt.getKeyChar());
        synchronized (meuFrame) {
            pressed.add(evt.getKeyCode());
            //verificaTeclas();
        }

    }                                        

    private void jButton_frutaKeyReleased(java.awt.event.KeyEvent evt) {                                          
        synchronized (meuFrame) {
            pressed.remove(evt.getKeyCode());
        }
    }                                         

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_jogoFrutinha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_jogoFrutinha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_jogoFrutinha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_jogoFrutinha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new JFrame_jogoFrutinha().setVisible(true);
            }
        });
    }
    int largura;
    int altura;
    int pontosJogador1 = 0;
    int pontosJogador2 = 0;

    // Variables declaration - do not modify                     
    public javax.swing.JButton jButton_fruta;
    public javax.swing.JButton jButton_jogador1;
    public javax.swing.JButton jButton_jogador2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField_jogador1;
    private javax.swing.JTextField jTextField_jogador2;
    // End of variables declaration                   
}
