
import java.util.HashSet;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JOptionPane;
import java.util.Random;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author alexandrezamberlan
 */
public class JFrame_paraTestes extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_paraTestes
     */
    public JFrame_paraTestes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_adicionar = new javax.swing.JButton();
        jPanel_area = new javax.swing.JPanel();
        jTextField_apelido = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton_adicionar.setText("adicionar");
        jButton_adicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_adicionarActionPerformed(evt);
            }
        });

        jPanel_area.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout jPanel_areaLayout = new javax.swing.GroupLayout(jPanel_area);
        jPanel_area.setLayout(jPanel_areaLayout);
        jPanel_areaLayout.setHorizontalGroup(
            jPanel_areaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel_areaLayout.setVerticalGroup(
            jPanel_areaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 397, Short.MAX_VALUE)
        );

        jLabel1.setText("Nome:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_area, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 276, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_apelido, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_adicionar))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_apelido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_adicionar)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_area, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_adicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_adicionarActionPerformed
        // TODO add your handling code here:
        if (jTextField_apelido.getText().equals("") || jTextField_apelido.getText().length() > 6) {
            JOptionPane.showMessageDialog(this, "Digite um nome primeiro e que tenha no máximo 6 caracteres");
        } else {
            try {
                //System.out.println("Vamos adicionar um novo componente com este nome: " + jTextField_apelido.getText());
                jTextField_apelido.requestFocus();
                jTextField_apelido.setText(jTextField_apelido.getText().toUpperCase());
                Random gerador = new Random();
                int largura = 80;
                int altura = 40;
                int x = gerador.nextInt(this.jPanel_area.getBounds().width - largura);
                int y = gerador.nextInt(this.jPanel_area.getBounds().height - altura);
                
                Componente c = new Componente(this.jTextField_apelido.getText(), x, y, largura, altura);
                
                if (!listaJogadores.contains(c)) {
                    listaJogadores.add(c);
                    //adiciona o botao no jPane_area
                    this.jPanel_area.add(listaJogadores.get(listaJogadores.size() - 1).botao);
                    listaJogadores.get(listaJogadores.size() - 1).botao.setVisible(true);
                    listaJogadores.get(listaJogadores.size() - 1).botao.setBounds(x, y, largura, altura);
                } else {
                    JOptionPane.showMessageDialog(this, this.jTextField_apelido.getText() + " já foi inserido!!");
                }

                jTextField_apelido.setText("");

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Problemas para inserir um jogador");
            }
        }

    }//GEN-LAST:event_jButton_adicionarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_paraTestes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_paraTestes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_paraTestes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_paraTestes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_paraTestes().setVisible(true);
            }
        });
    }

    List<Componente> listaJogadores = new LinkedList<>();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_adicionar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel_area;
    private javax.swing.JTextField jTextField_apelido;
    // End of variables declaration//GEN-END:variables
}
